apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: ops@jems0906.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flagplane-tls
  namespace: flagplane
spec:
  secretName: flagplane-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: api.flagplane.jems0906.dev
  dnsNames:
    - api.flagplane.jems0906.dev
    - demo.flagplane.jems0906.dev
    - grafana.flagplane.jems0906.dev
