apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: flagplane-daily
  namespace: velero
spec:
  schedule: "0 2 * * *"
  template:
    includedNamespaces:
      - flagplane
    snapshotVolumes: true
    ttl: 720h0m0s
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: flagplane-hourly
  namespace: velero
spec:
  schedule: "0 * * * *"
  template:
    includedNamespaces:
      - flagplane
    snapshotVolumes: true
    ttl: 168h0m0s
